/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_opencv_MainActivity */

#ifndef _Included_com_example_opencv_MainActivity
#define _Included_com_example_opencv_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_opencv_MainActivity
 * Method:    getEdge
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_example_opencv_MainActivity_getEdge
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_example_opencv_MainActivity
 * Method:    stringFromJNI
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_opencv_MainActivity_getBarcode
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
